### ISSUE TITLE
Getting the following error while trying to run the python app.py command

### ISSUE THREAD

**Issue by daniyaunissa** [turhancan97/Intelligent-Face-Recognition-Attendance-System#3]
C:\Users\daniy\Projects\Intelligent-Face-Recognition-Attendance-System>python app.py
2024-10-22 23:51:02.673761: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-10-22 23:51:02.673950: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:\Users\daniy\Projects\Intelligent-Face-Recognition-Attendance-System\app.py", line 12, in <module>
    from detection.face_matching import detect_faces, align_face
  File "C:\Users\daniy\Projects\Intelligent-Face-Recognition-Attendance-System\detection\__init__.py", line 1, in <module>
    from .face_matching import *
  File "C:\Users\daniy\Projects\Intelligent-Face-Recognition-Attendance-System\detection\face_matching.py", line 19, in <module>
    predictor = dlib.shape_predictor(datFile)
RuntimeError: Unable to open /Users/turhancan97/Library/CloudStorage/OneDrive-AnadoluÜniversitesi-AÖF/Side Projetcs/Others/Güncel Projeler/Face_Recognition_App/Intelligent-Face-Recognition-Attendance-System/detection/shape_predictor_68_face_landmarks.dat

**Comment by turhancan97** [comment]
you need to download the shape predictor file 'shape_predictor_68_face_landmarks.dat' from the dlib website. You can download the file from [here](https://github.com/italojs/facial-landmarks-recognition/blob/master/shape_predictor_68_face_landmarks.dat). You can put the file in the detection folder and you need to write full path of the file in the face_matching.py file for the datFile variable as below.

![image](https://github.com/user-attachments/assets/309962c6-3db8-4f15-9e96-b891ea464341)

**Comment by Megharajgit** [comment]
I am unable to implement it properly can I get any tutorial video

**Comment by daniyaunissa** [comment]
> you need to download the shape predictor file 'shape_predictor_68_face_landmarks.dat' from the dlib website. You can download the file from [here](https://github.com/italojs/facial-landmarks-recognition/blob/master/shape_predictor_68_face_landmarks.dat). You can put the file in the detection folder and you need to write full path of the file in the face_matching.py file for the datFile variable as below.
> 
I have done the same and path for the file is "C:\windows\System32\Intelligent-Face-Recognition-Attendance-System\detection\shape_predictor_68_face_landmarks (2).dat" . But in the  image there is different path. Getting error in import cv line of face_matching.py

**Comment by turhancan97** [comment]
Can you please send me the full error?

**Comment by daniyaunissa** [comment]
> Can you please send me the full error?

![Screenshot 2024-10-24 011154](https://github.com/user-attachments/assets/81e99657-77ff-4abc-ae00-52689c0397b0)

**Comment by daniyaunissa** [comment]
while running the program getting this error

**Comment by turhancan97** [comment]
It seems you didn't install the environment properly.

**Comment by daniyaunissa** [comment]
> It seems you didn't install the environment properly.

Can we connect regarding this so you can check where it went wrong
